####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode
#
# Before building the docker image run:
#
# mvn package -Pnative -Dquarkus.native.container-build=true
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-alpine -t quarkus/performance-test .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/performance-test
#
###
#FROM registry.access.redhat.com/ubi8/ubi-minimal:8.1
FROM alpine
ENV PG_USER=username \
    PG_PWD=password \
    PG_HOST_NAME=host.docker.internal \
    PG_HOST_PORT=5432 \
    LOG_DIR=/var/log/application

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work \
    && mkdir ${LOG_DIR} \
    && chmod "a+rwx" ${LOG_DIR}
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
